apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kafka_exporters-api-kafka_exporters_v1
  namespace: core
  title: "KafkaExportersService v1"
  labels:
    api-type: "api"
    api-version: "v1"
    api-component: "kafka_exporters"
spec:
  type: grpc
  lifecycle: production
  owner: core-team
  definition: |
    syntax = "proto3";
    
    package strmprivacy.api.kafka_exporters.v1;
    
    import "google/api/field_behavior.proto";
    import "strmprivacy/api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/api/kafka_exporters/v1;kafka_exporters";
    option java_package = "io.strmprivacy.api.kafka_exporters.v1";
    option java_multiple_files = true;
    
    service KafkaExportersService {
      rpc ListKafkaExporters (ListKafkaExportersRequest) returns (ListKafkaExportersResponse);
      rpc GetKafkaExporter (GetKafkaExporterRequest) returns (GetKafkaExporterResponse);
      rpc DeleteKafkaExporter (DeleteKafkaExporterRequest) returns (DeleteKafkaExporterResponse);
      rpc CreateKafkaExporter (CreateKafkaExporterRequest) returns (CreateKafkaExporterResponse);
    }
    
    message ListKafkaExportersRequest {
      string billing_id = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
    }
    
    message ListKafkaExportersResponse {
      repeated strmprivacy.api.entities.v1.KafkaExporter kafka_exporters = 1;
    }
    
    message DeleteKafkaExporterRequest {
      entities.v1.KafkaExporterRef ref = 1 [(google.api.field_behavior) = REQUIRED];
      // (-- api-linter: core::0135::request-unknown-fields=disabled
      //     aip.dev/not-precedent: We really need this field. --)
      bool recursive = 2 [(google.api.field_behavior) = REQUIRED];
    }
    
    message DeleteKafkaExporterResponse {
    }
    
    message CreateKafkaExporterRequest {
      strmprivacy.api.entities.v1.KafkaExporter kafka_exporter = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message CreateKafkaExporterResponse {
      strmprivacy.api.entities.v1.KafkaExporter kafka_exporter = 1;
    }
    
    message GetKafkaExporterRequest {
      entities.v1.KafkaExporterRef ref = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetKafkaExporterResponse {
      strmprivacy.api.entities.v1.KafkaExporter kafka_exporter = 1;
    }
