apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-ProjectsService-v1
  title: "ProjectsService v1"
  labels:
    api-type: "api"
    api-version: "v1"
    api-component: "projects"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.api.projects.v1;
    
    import "google/api/field_behavior.proto";
    import "strmprivacy/api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/api/projects/v1;projects";
    option java_package = "io.strmprivacy.api.projects.v1";
    option java_multiple_files = true;
    
    service ProjectsService {
      rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
      rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse);
      rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse);
      rpc GetProject(GetProjectRequest) returns (GetProjectResponse);
    }
    
    message GetProjectRequest {
      string project_id = 1;
    }
    
    message GetProjectResponse {
      strmprivacy.api.entities.v1.Project project = 1;
    }
    
    message ListProjectsRequest {}
    
    message ListProjectsResponse {
      repeated strmprivacy.api.entities.v1.Project projects = 1;
    }
    
    // (-- api-linter: core::0133::request-resource-field=disabled
    //     aip.dev/not-precedent: As we do not know anything about the project to create yet, create message is empty. --)
    message CreateProjectRequest {
      strmprivacy.api.entities.v1.Project project = 1;
    }
    
    message CreateProjectResponse {
      strmprivacy.api.entities.v1.Project project = 1;
    }
    
    message DeleteProjectRequest {
      string project_id = 1;
    }
    
    message DeleteProjectResponse {}
