apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: metrics-api-metrics
  namespace: core
  title: "MetricsService v1"
  labels:
    api-type: "api"
    api-version: "v1"
    api-component: "metrics"
spec:
  type: grpc
  lifecycle: production
  owner: core-team
  definition: |
    syntax = "proto3";
    
    package strmprivacy.api.metrics.v1;
    
    import "google/api/field_behavior.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/api/metrics/v1;metrics";
    option java_package = "io.strmprivacy.api.metrics.v1";
    option java_multiple_files = true;
    
    service MetricsService {
      rpc GetSystemState(GetSystemStateRequest) returns (GetSystemStateResponse);
    }
    
    message GetSystemStateRequest {
    }
    
    message GetSystemStateResponse {
      SystemState overall_state = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
    }
    
    enum SystemState {
      SYSTEM_STATE_UNSPECIFIED = 0;
    
      // Everything is working fine (green).
      UP = 1;
    
      // One or more major parts of the system are down/unusable (red).
      MAJOR_DOWN = 2;
    
      // Small parts of the system are down/unusable, but the core is not affected. (orange).
      MINOR_DOWN = 3;
    }
