apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-StreamsAgentService-v1
  title: "StreamsAgentService v1"
  labels:
    api-type: "api"
    api-version: "v1"
    api-component: "agents"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.api.agents.v1;
    
    import "strmprivacy/api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/api/agents/v1;agents";
    option java_package = "io.strmprivacy.api.agents.v1";
    option java_multiple_files = true;
    
    // (-- api-linter: core::0136::prepositions=disabled
    //     aip.dev/not-precedent: This is an internal API and the alternative with oneof is good either. --)
    service StreamsAgentService {
      rpc GetStreams(GetStreamsRequest) returns (GetStreamsResponse);
    }
    
    message GetStreamsRequest {
    }
    
    message GetStreamsResponse {
      repeated strmprivacy.api.entities.v1.ExtendedStream extended_streams = 1;
    }
