apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-BatchJobsService-v1
  title: "BatchJobsService v1"
  labels:
    api-type: "api"
    api-version: "v1"
    api-component: "batch_jobs"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.api.batch_jobs.v1;
    
    import "google/api/field_behavior.proto";
    import "strmprivacy/api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/api/batch_jobs/v1;batch_jobs";
    option java_package = "io.strmprivacy.api.batch_jobs.v1";
    option java_multiple_files = true;
    
    service BatchJobsService {
      rpc GetBatchJob(GetBatchJobRequest) returns (GetBatchJobResponse);
      rpc ListBatchJobs(ListBatchJobsRequest) returns (ListBatchJobsResponse);
      rpc CreateBatchJob(CreateBatchJobRequest) returns (CreateBatchJobResponse);
      rpc DeleteBatchJob(DeleteBatchJobRequest) returns (DeleteBatchJobResponse);
      rpc UpdateBatchJobState(UpdateBatchJobStateRequest) returns (UpdateBatchJobStateResponse);
    }
    
    message GetBatchJobRequest {
      entities.v1.BatchJobRef ref = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetBatchJobResponse {
      entities.v1.BatchJob batch_job = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message ListBatchJobsRequest {
      string billing_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message ListBatchJobsResponse {
      repeated entities.v1.BatchJob batch_jobs = 1;
    }
    
    message CreateBatchJobRequest {
      entities.v1.BatchJob batch_job = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message CreateBatchJobResponse {
      entities.v1.BatchJob batch_job = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message DeleteBatchJobRequest {
      entities.v1.BatchJobRef ref = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message DeleteBatchJobResponse {
    }
    
    // (-- api-linter: core::0134::request-mask-required=disabled
    //     aip.dev/not-precedent: This RPC only updates one field. --)
    message UpdateBatchJobStateRequest {
      entities.v1.BatchJobRef ref = 1 [(google.api.field_behavior) = REQUIRED];
      entities.v1.BatchJobState batch_job_state = 2 [(google.api.field_behavior) = REQUIRED];
    }
    
    message UpdateBatchJobStateResponse {
    }
