apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: internal_api-InternalEventContractsService-v1
  title: "InternalEventContractsService v1"
  labels:
    api-type: "internal_api"
    api-version: "v1"
    api-component: "event_contracts"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.internal_api.event_contracts.v1;
    
    import "strmprivacy/api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/internal_api/event_contracts/v1;event_contracts";
    option java_package = "io.strmprivacy.internal_api.event_contracts.v1";
    option java_multiple_files = true;
    
    service InternalEventContractsService {
      rpc GetEventContractAndSchema (GetEventContractAndSchemaRequest) returns (GetEventContractAndSchemaResponse);
    }
    
    message GetEventContractAndSchemaRequest {
      strmprivacy.api.entities.v1.EventContractRef ref = 1;
    }
    
    message GetEventContractAndSchemaResponse {
      strmprivacy.api.entities.v1.EventContract event_contract = 1;
      strmprivacy.api.entities.v1.Schema schema = 2;
      int32 confluent_id = 3;
    }
