apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: internal_api-StrmAgentOperatorService-v1
  namespace: core
  title: "StrmAgentOperatorService v1"
  labels:
    api-type: "internal_api"
    api-version: "v1"
    api-component: "agents"
spec:
  type: grpc
  lifecycle: production
  owner: core-team
  subcomponentOf: core/api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.internal_api.agents.v1;
    
    import "strmprivacy/internal_api/entities/v1/entities_v1.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/internal_api/agents/v1;agents";
    option java_package = "io.strmprivacy.internal_api.agents.v1";
    option java_multiple_files = true;
    
    service StrmAgentOperatorService {
      rpc GetAgentVersions(GetAgentVersionsRequest) returns (GetAgentVersionsResponse);
    }
    
    message GetAgentVersionsRequest {
    }
    
    message GetAgentVersionsResponse {
      repeated strmprivacy.internal_api.entities.v1.KubernetesDeployment deployments = 1;
    }
    
    
