apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: internal_api-InternalAccountService-v1
  title: "InternalAccountService v1"
  labels:
    api-type: "internal_api"
    api-version: "v1"
    api-component: "account"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.internal_api.account.v1;
    
    import "google/api/field_behavior.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/internal_api/account/v1;account";
    option java_package = "io.strmprivacy.internal_api.account.v1";
    option java_multiple_files = true;
    
    service InternalAccountService {
      /* Unfortunately, this internal API is required, as we cannot set headers per request with Kotlin gRPC */
      rpc GetLegacyBillingId (GetLegacyBillingIdRequest) returns (GetLegacyBillingIdResponse);
    }
    
    message GetLegacyBillingIdRequest {
      string external_user_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetLegacyBillingIdResponse {
      string billing_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
