apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: internal_api-InternalAccountService-v1
  title: "InternalAccountService v1"
  labels:
    api-type: "internal_api"
    api-version: "v1"
    api-component: "account"
spec:
  type: grpc
  lifecycle: production
  owner: team-core
  system: api-definitions
  definition: |
    syntax = "proto3";
    
    package strmprivacy.internal_api.account.v1;
    
    import "google/api/field_behavior.proto";
    
    option go_package = "github.com/strmprivacy/api-definitions-go/v2/internal_api/account/v1;account";
    option java_package = "io.strmprivacy.internal_api.account.v1";
    option java_multiple_files = true;
    
    service InternalAccountService {
      /* Unfortunately, this internal API is required, as we cannot set headers per request with Kotlin gRPC */
      rpc GetLegacyBillingId(GetLegacyBillingIdRequest) returns (GetLegacyBillingIdResponse);
    
      // Temporary API from SOS to OMA to map from billing_account_id to billing_id
      // (-- api-linter: core::0136::prepositions=disabled
      //     aip.dev/not-precedent: Temporary method, can't think of a better name. --)
      rpc GetLegacyBillingIdByBillingAccountId(GetLegacyBillingIdByBillingAccountIdRequest) returns (GetLegacyBillingIdByBillingAccountIdResponse);
    }
    
    message GetLegacyBillingIdRequest {
      option deprecated = true;
      string external_user_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetLegacyBillingIdResponse {
      option deprecated = true;
      string billing_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetLegacyBillingIdByBillingAccountIdRequest {
      option deprecated = true;
      string billing_account_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
    
    message GetLegacyBillingIdByBillingAccountIdResponse {
      option deprecated = true;
      string billing_id = 1 [(google.api.field_behavior) = REQUIRED];
    }
