include:
  - project: 'stream-machine/tools-and-utilities/ci-templates'
    file: '/common/semantic-release.yml'
  - local: '.gitlab/go.yml'
  - local: '.gitlab/jvm.yml'
  - local: '.gitlab/lint-and-breaking.yml'
  - local: '.gitlab/python.yml'
  - local: '.gitlab/typescript.yml'

stages:
  - lint-and-breaking
  - generate
  - release
  - publish

release:
  stage: release
  extends: .semantic-release
