include:
  - project: 'stream-machine/tools-and-utilities/ci-templates'
    file: '/gradle/build-and-test.yml'
  - project: 'stream-machine/tools-and-utilities/ci-templates'
    file: '/gradle/jar-publish.yml'
  - project: 'stream-machine/tools-and-utilities/ci-templates'
    file: '/common/semantic-release.yml'

stages:
  - lint
  - breaking-change
  - release
  - publish

.buf:
  image: bufbuild/buf:latest
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stream-machine/tools-and-utilities/google-api-linter.git
  except: # Do not run for tag pipelines and also do not run for master pipelines when it's a release commit
    variables:
      - ($CI_BUILD_REF_NAME == "master" && $CI_COMMIT_MESSAGE =~ /.*chore\(release\).*/) || $CI_COMMIT_TAG

buf-lint:
  extends: .buf
  stage: lint
  script:
    - buf lint

aip-guidelines-lint:
  stage: lint
  image: eu.gcr.io/stream-machine-development/google/api-linter:1.25.0
  script:
    - ./api-linter.sh

breaking:
 extends: .buf
 stage: breaking-change
 script:
   - export LATEST_TAG=$(git tag -l | sort -V | tail -n 1)
   - echo "Latest tag = $LATEST_TAG"
   - if [ ! -z "$LATEST_TAG" ] ; then buf breaking --against ".git#tag=$LATEST_TAG"; fi

release:
  stage: release
  extends: .semantic-release

artifact-snapshot:
  stage: publish
  extends: .jar-snapshot-template
  script:
    - ./gradlew --build-cache publish

artifact-release:
  stage: publish
  extends: .jar-release-template
  script:
    - ./gradlew --build-cache publish

