site_name: 'API Definitions'

nav:
  - Home: index.md
  - Future Improvements: future_improvements.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.superfences
